title: "Quinta do Mosteiro"
email: mail@quintadomosteiro.com
description:
    pt: "Quinta de charme para aluguer, localizada em Ponte da Barca, Portugal"
    en: "Boutique property for rental, located in Ponte da Barca, Portugal"
baseurl: ""
url: "https://quintadomosteiro.com"
cdn_url: ""
markdown: kramdown
default_lang: pt

kramdown:
  input: GFM
  syntax_highlighter: null