title: "Quinta do Mosteiro"
email: mail@quintadomosteiro.net
description:
    pt: "Ponte da Barca, Portugal"
    en: "Ponte da Barca, Portugal"
baseurl: ""
phone_number: +351 916 524 180
url: "https://quintadomosteiro.net"
cdn_url: ""
markdown: kramdown
default_lang: pt

kramdown:
  input: GFM
  syntax_highlighter: null

# Serving
detach:  false
port:    4100
host:    0.0.0.0
